Repository Re-quire/yummy, pull requests merged in 2025-01, with the labels that each got.

#22 Feat/setup cd pipeline
  .github/workflows/CI.yml
  .github/workflows/deploy.yml
  Dockerfile
  application/src/main/resources/application-local.yml
  application/src/main/resources/application.yml
Labels: feature

#21 feat: OAuth2 구현 및 User 도메인 생성
  application/build.gradle
  application/src/main/java/com/groom/yummy/config/SecurityConfig.java
  application/src/main/java/com/groom/yummy/exception/CustomAccessDeniedHandler.java
  application/src/main/java/com/groom/yummy/exception/CustomAuthenticationEntryPoint.java
  application/src/main/java/com/groom/yummy/filter/JwtAuthFilter.java
  application/src/main/java/com/groom/yummy/oauth2/auth/LoginUser.java
  application/src/main/java/com/groom/yummy/oauth2/dto/KakaoResponse.java
  application/src/main/java/com/groom/yummy/oauth2/dto/OAuth2Response.java
  application/src/main/java/com/groom/yummy/oauth2/handler/CustomSuccessHandler.java
  application/src/main/java/com/groom/yummy/oauth2/service/CustomOAuth2UserService.java
  application/src/main/java/com/groom/yummy/oauth2/strategy/KakaoOAuth2ResStrategy.java
  application/src/main/java/com/groom/yummy/oauth2/strategy/OAuth2ResFactory.java
  application/src/main/java/com/groom/yummy/oauth2/strategy/OAuth2ResStrategy.java
  application/src/main/java/com/groom/yummy/util/CookieUtil.java
  application/src/main/java/com/groom/yummy/util/JwtUtil.java
  application/src/main/resources/application-local.yml
  build.gradle
  domain/build.gradle
  domain/src/main/java/com/groom/yummy/user/User.java
  domain/src/main/java/com/groom/yummy/user/UserAuthService.java
  domain/src/main/java/com/groom/yummy/user/UserRepository.java
  settings.gradle
  storage/build.gradle
  storage/src/main/java/com/groom/yummy/domain/BaseEntity.java
  storage/src/main/java/com/groom/yummy/domain/region/RegionEntity.java
  storage/src/main/java/com/groom/yummy/domain/user/UserEntity.java
  storage/src/main/java/com/groom/yummy/domain/user/UserEntityRepository.java
  storage/src/main/java/com/groom/yummy/domain/user/UserJpaRepository.java
Labels: feature

#25 refactor: migration Docker hub to AWS ECR
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  Dockerfile
  application/src/main/resources/application-dev.yml
  application/src/main/resources/application-local.yml
  application/src/main/resources/application-test.yml
  application/src/main/resources/application.yml
Labels: refactor

#26 feat: OAuth2 기능 완성, User 도메인 추가
  application/build.gradle
  application/src/main/java/com/groom/yummy/config/CorsMvcConfig.java
  application/src/main/java/com/groom/yummy/config/SecurityConfig.java
  application/src/main/java/com/groom/yummy/config/SwaggerConfig.java
  application/src/main/java/com/groom/yummy/controller/UserController.java
  application/src/main/java/com/groom/yummy/exception/CustomAccessDeniedHandler.java
  application/src/main/java/com/groom/yummy/exception/CustomAuthenticationEntryPoint.java
  application/src/main/java/com/groom/yummy/filter/JwtAuthFilter.java
  application/src/main/java/com/groom/yummy/jwt/JwtProvider.java
  application/src/main/java/com/groom/yummy/oauth2/auth/LoginUser.java
  application/src/main/java/com/groom/yummy/oauth2/handler/CustomSuccessHandler.java
  application/src/main/java/com/groom/yummy/oauth2/service/CustomOAuth2UserService.java
  application/src/main/java/com/groom/yummy/resolver/AuthUserResolver.java
  application/src/main/java/com/groom/yummy/util/CookieUtil.java
  application/src/main/java/com/groom/yummy/util/JwtUtil.java
  application/src/main/resources/application-local.yml
  common/build.gradle
  common/src/main/java/com/groom/yummy/dto/ResponseDto.java
  common/src/main/java/com/groom/yummy/exception/CustomException.java
  common/src/main/java/com/groom/yummy/exception/ErrorCode.java
  common/src/main/java/exception/CustomException.java
  common/src/main/java/exception/ErrorCode.java
  domain/build.gradle
  domain/src/main/java/com/groom/yummy/dto/request/UpdateNicknameReqDto.java
  domain/src/main/java/com/groom/yummy/dto/response/UserInfoResDto.java
  domain/src/main/java/com/groom/yummy/facade/UserFacade.java
  domain/src/main/java/com/groom/yummy/publisher/EventPublisher.java
  domain/src/main/java/com/groom/yummy/publisher/SpringEventPublisher.java
  domain/src/main/java/com/groom/yummy/user/User.java
  domain/src/main/java/com/groom/yummy/user/UserAuthService.java
  domain/src/main/java/com/groom/yummy/user/UserDeleteEvent.java
  domain/src/main/java/com/groom/yummy/user/UserNicknameChangedEvent.java
  domain/src/main/java/com/groom/yummy/user/UserRepository.java
  domain/src/main/java/com/groom/yummy/user/UserService.java
  storage/src/main/java/com/groom/yummy/domain/user/UserEntity.java
  storage/src/main/java/com/groom/yummy/domain/user/UserEntityRepository.java
  storage/src/main/java/com/groom/yummy/handler/UserEventHandler.java
Labels: feature

#28 test: OAuth2 , User 관련 테스트 코드를 작성
  application/build.gradle
  application/src/main/java/com/groom/yummy/YummyApplication.java
  application/src/main/java/com/groom/yummy/controller/UserController.java
  application/src/main/java/com/groom/yummy/filter/JwtAuthFilter.java
  application/src/main/java/com/groom/yummy/oauth2/handler/CustomSuccessHandler.java
  application/src/main/java/com/groom/yummy/oauth2/service/CustomOAuth2UserService.java
  application/src/main/resources/application.yml
  application/src/test/java/com/groom/yummy/controller/UserControllerTest.java
  application/src/test/java/com/groom/yummy/oauth2/handler/CustomSuccessHandlerTest.java
  application/src/test/java/com/groom/yummy/oauth2/service/CustomOAuth2UserServiceTest.java
  application/src/test/java/module/ControllerTestSupport.java
  domain/build.gradle
  domain/src/main/java/com/groom/yummy/user/UserAuthService.java
  domain/src/main/java/com/groom/yummy/user/UserRepository.java
  domain/src/main/java/com/groom/yummy/user/UserService.java
  domain/src/test/java/com/groom/yummy/facade/UserFacadeTest.java
  domain/src/test/java/com/groom/yummy/user/UserAuthServiceTest.java
  storage/build.gradle
  storage/src/main/java/com/groom/yummy/config/H2Config.java
  storage/src/main/java/com/groom/yummy/domain/user/UserEntityRepository.java
  storage/src/test/java/com/groom/yummy/TestApplication.java
  storage/src/test/java/com/groom/yummy/domain/user/UserEntityRepositoryTest.java
  storage/src/test/java/com/groom/yummy/handler/UserEventHandlerTest.java
Labels: test

#32 Feat/reply
  application/build.gradle
  application/src/main/java/com/groom/yummy/config/SecurityConfig.java
  application/src/main/java/com/groom/yummy/controller/GroupController.java
  application/src/main/java/com/groom/yummy/controller/ReplyController.java
  application/src/main/java/com/groom/yummy/reply/dto/ReplyRequestDto.java
  application/src/main/java/com/groom/yummy/reply/dto/ReplyResponseDto.java
  application/src/main/java/com/groom/yummy/reply/dto/ReplyUpdateRequestDto.java
  application/src/main/resources/application.yml
  application/src/test/java/com/groom/yummy/controller/ReplyControllerTest.java
  domain/build.gradle
  domain/src/main/java/com/groom/yummy/reply/Reply.java
  domain/src/main/java/com/groom/yummy/reply/ReplyRepository.java
  domain/src/main/java/com/groom/yummy/reply/ReplyService.java
  domain/src/main/java/com/groom/yummy/reply/event/ReplyUpdatedEvent.java
  domain/src/test/java/com/groom/yummy/reply/ReplyServiceTest.java
  storage/src/main/java/com/groom/yummy/domain/reply/ReplyEntity.java
  storage/src/main/java/com/groom/yummy/domain/reply/ReplyEntityRepository.java
  storage/src/main/java/com/groom/yummy/domain/reply/ReplyJpaRepository.java
  storage/src/main/java/com/groom/yummy/domain/user/UserEntityRepository.java
  storage/src/main/java/com/groom/yummy/handler/ReplyEventListener.java
Labels: feature

#34 feat: 예외처리 클래스 및 에러 코드 추가
  application/src/main/java/com/groom/yummy/YummyApplication.java
  application/src/main/java/com/groom/yummy/config/SecurityConfig.java
  application/src/main/java/com/groom/yummy/controller/UserController.java
  application/src/main/java/com/groom/yummy/exception/GlobalExceptionHandler.java
  application/src/main/java/com/groom/yummy/exception/JwtErrorCode.java
  application/src/main/java/com/groom/yummy/exception/handler/RestControllerExceptionHandler.java
  application/src/main/java/com/groom/yummy/exception/security/CustomAccessDeniedHandler.java
  application/src/main/java/com/groom/yummy/exception/security/CustomAuthenticationEntryPoint.java
  application/src/main/java/com/groom/yummy/filter/JwtAuthFilter.java
  application/src/main/java/com/groom/yummy/jwt/JwtProvider.java
  application/src/main/java/com/groom/yummy/oauth2/service/CustomOAuth2UserService.java
  application/src/main/resources/application.yml
  application/src/test/java/com/groom/yummy/controller/UserControllerTest.java
  application/src/test/java/com/groom/yummy/oauth2/service/CustomOAuth2UserServiceTest.java
  common/build.gradle
  common/src/main/java/com/groom/yummy/dto/ResponseDto.java
  common/src/main/java/com/groom/yummy/exception/CustomException.java
  common/src/main/java/com/groom/yummy/exception/ErrorCode.java
  domain/build.gradle
  domain/src/main/java/com/groom/yummy/exception/UserErrorCode.java
  domain/src/main/java/com/groom/yummy/exception/handler/CustomExceptionHandler.java
  domain/src/main/java/com/groom/yummy/user/UserService.java
  domain/src/main/java/com/groom/yummy/user/dto/request/UpdateNicknameReqDto.java
  domain/src/main/java/com/groom/yummy/user/dto/response/UserInfoResDto.java
  domain/src/main/java/com/groom/yummy/user/event/UserDeleteEvent.java
  domain/src/main/java/com/groom/yummy/user/event/UserNicknameChangedEvent.java
  domain/src/main/java/com/groom/yummy/user/facade/UserFacade.java
  domain/src/test/java/com/groom/yummy/facade/UserFacadeTest.java
  storage/build.gradle
  storage/src/main/java/com/groom/yummy/handler/UserEventHandler.java
  storage/src/test/java/com/groom/yummy/handler/UserEventHandlerTest.java
Labels: feature

#39 Feat/add jacoco multimodule
  application/build.gradle
  application/src/test/java/com/groom/yummy/oauth2/service/SomeApiServiceTest.java
  build.gradle
  storage/build.gradle
Labels: feature

#42 feat: testUser 기능 추가
  application/src/main/java/com/groom/yummy/config/SecurityConfig.java
  application/src/main/java/com/groom/yummy/controller/StoreController.java
  application/src/main/java/com/groom/yummy/external/StoreApiClient.java
  application/src/main/java/com/groom/yummy/external/dto/ApiResponse.java
  application/src/main/java/com/groom/yummy/external/dto/PaginationInfo.java
  application/src/main/java/com/groom/yummy/external/dto/StoreListResponse.java
  application/src/main/java/com/groom/yummy/external/dto/StoreRequestDto.java
  application/src/main/java/com/groom/yummy/external/dto/StoreResponseDto.java
  application/src/main/java/com/groom/yummy/test/TestCreateController.java
  application/src/main/java/com/groom/yummy/test/dto/SignInDto.java
  application/src/main/java/com/groom/yummy/test/dto/TestUserCreateDto.java
  application/src/main/java/com/groom/yummy/test/dto/TestUserResDto.java
  application/src/main/resources/application.yml
  application/src/test/java/com/groom/yummy/controller/UserControllerTest.java
Labels: feature

#44 fix: 실행 테스트 하며 수정
  application/src/main/java/com/groom/yummy/config/SecurityConfig.java
  application/src/main/java/com/groom/yummy/config/WebClientConfig.java
  application/src/main/java/com/groom/yummy/controller/StoreController.java
  application/src/main/java/com/groom/yummy/external/Category.java
  application/src/main/java/com/groom/yummy/external/StoreApiClient.java
  application/src/main/java/com/groom/yummy/external/dto/StoreRequestDto.java
  application/src/main/java/com/groom/yummy/external/dto/StoreResponseDto.java
  application/src/main/java/com/groom/yummy/oauth2/handler/CustomSuccessHandler.java
  application/src/main/java/com/groom/yummy/test/TestCreateController.java
  application/src/main/java/com/groom/yummy/webclient/SomeApiService.java
  application/src/main/resources/application.yml
  domain/src/main/java/com/groom/yummy/group/GroupRepository.java
  domain/src/main/java/com/groom/yummy/group/GroupService.java
  domain/src/main/java/com/groom/yummy/group/dto/request/CreateGroupRequestDto.java
  domain/src/main/java/com/groom/yummy/group/dto/request/JoinGroupRequestDto.java
  domain/src/main/java/com/groom/yummy/store/Category_.java
  domain/src/main/java/com/groom/yummy/store/Store.java
  domain/src/main/java/com/groom/yummy/store/StoreService.java
  domain/src/main/java/com/groom/yummy/usertogroup/UserToGroupRepository.java
  domain/src/test/java/com/groom/yummy/group/GroupServiceTest.java
  domain/src/test/java/com/groom/yummy/store/StoreServiceTest.java
  storage/src/main/java/com/groom/yummy/domain/group/GroupEntity.java
  storage/src/main/java/com/groom/yummy/domain/group/GroupEntityRepository.java
  storage/src/main/java/com/groom/yummy/domain/store/StoreEntity.java
  storage/src/main/java/com/groom/yummy/domain/usertogroup/UserToGroupEntity.java
  storage/src/main/java/com/groom/yummy/domain/usertogroup/UserToGroupEntityRepository.java
Labels: refactor
